#main default
application: todoscast
version: 1-02
runtime: go
api_version: go1

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
#the above list is default
- ^(.*/)?.*.sh$
- ^(.*/)?.*_test.go$
- ^(.*/)?.*.md$
- ^layout$
- ^todos$


handlers:  
- url: /icon.png
  static_files: static/icon.png
  upload: static/icon.png
- url: /css
  static_dir: static/css
- url: /images
  static_dir: static/images
- url: /js
  static_dir: static/js
- url: /_ah/remote_api
  script: _go_app
- url: /.*
  script: _go_app
