#chat module
application: todoscast
version: 1-01
module: chat
runtime: go
api_version: go1

inbound_services:
- channel_presence

handlers:
- url: /.*
  script: _go_app
  login: required
  secure: always
  redirect_http_response_code: 301
